### ISSUE TITLE
I have an oldish AA save file that crashes the editor (and the other editor).

### ISSUE THREAD

**Issue by B3bomber** [geneishouko/AA2QtEdit#5]
I was hoping to make a backup of the girls I made in it. I keep forgetting to do that occasionally.

Link to save file.
https://files.catbox.moe/7dcj6z.sav

Rave学園1年1組_1.sav is the actual name of the save file. Hopefully you have some luck there. It still loads in game.

**Comment by geneishouko** [comment]
AA2QtEdit can't open AA1 class saves. However I'll add check so that it doesn't crash anymore.
